apiVersion: v1
kind: Service
metadata:
  name: hello-flask-app
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.serviceport }}
      targetPort: 8888
  selector:
    app: hello-flask-app
